export const FETCH_RANDOM_USERS_BEGIN   = 'FETCH_RANDOM_USERS_BEGIN';
export const FETCH_RANDOM_USERS_SUCCESS = 'FETCH_RANDOM_USERS_SUCCESS';
export const FETCH_RANDOM_USERS_FAILURE = 'FETCH_RANDOM_USERS_FAILURE';